import type { NextPage } from "next";
import Head from "next/head";
import Search from "~/components/Search";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>OraciFood</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen  bg-gradient-to-b from-[#212529] to-[#212529] text-white">
        <Search/>
      </main>
    </>
  );
};

export default Home;
